### ISSUE TITLE
Sequence

### ISSUE THREAD

**Issue by 0jay** [nutterpc/tg-luci#1]
Step 4 refers to files extracted in step 2 (should refer to step 3)

**Comment by nutterpc** [comment]
Thanks for pointing that out, I might consolidate that line. Gimme a few mins

**Comment by 0jay** [comment]
No worries, absolutely fantastic effort you’ve made.
Just bloody fantastic.

**Comment by nutterpc** [comment]
Steps consolidated as per suggestion
