### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by lorenzocanale-LC** [nutterpc/tg-luci#17]
Model: TG789vac V2
Firmware: 17.2
When trying to run the install.sh the modem returned "Segmentation Fault". I fixed removing this [logger() {
	logger -s -t "tg-LuCI Install Script:" "$1"
	echo "$1"
}] from the script, but I didn't receive any message during the installation. 
The script worked well though and everything was working fine after the reboot.

**Comment by FrancYescO** [comment]
fixed with https://github.com/nutterpc/tg-luci/pull/16
