### ISSUE TITLE
WIFI Reporting

### ISSUE THREAD

**Issue by nutterpc** [nutterpc/tg-luci#18]
This is mainly for me, to remind myself to finalise the reporting for wifi.

There still is minor glitches inside reporting, but by & large it works

**Comment by kevdagoat** [comment]
Have to get back into developing these gui’s! Been doing other stuff for a while

**Comment by FrancYescO** [comment]
could you explain steps that allowed you to reach this goal?
https://forums.whirlpool.net.au/forum-replies.cfm?t=2650998&p=119#r2379

**Comment by FrancYescO** [comment]
news?

**Comment by nutterpc** [comment]
Will be working a bit more on it this weekend hopefully. Depends how much time I've got free

**Comment by nutterpc** [comment]
Currently working to best expected capability without Unlocked bootloader

**Comment by FrancYescO** [comment]
so the wifi management thought luci is not possible? O.o
