### ISSUE TITLE
789vac v2 Install report

### ISSUE THREAD

**Issue by FrancYescO** [nutterpc/tg-luci#2]
Fully installed on 789vac v2 with Firmware UNO 17.2

Basically Luci works but not the wireless part and during executing of sh script there are a lot of error messages:

![image](https://user-images.githubusercontent.com/4574593/45927020-c8046e80-bf2c-11e8-946b-194243e2a072.png)

[scriptlog.txt](https://github.com/nutterpc/tg-luci/files/2408623/scriptlog.txt)

ps, you should point out that a WAN connection is required (and the easiest way to get is is to put a gateway in the script the is not the modem where you are installing) probably a better way to get it is to not fully clean the network config file but just fix what is needed for luci... or in general take the script less "aggressive"

**Comment by nutterpc** [comment]
Oh the Wireless part I know of, the workaround I had in place for the Wireless will do *for now*.

And I can adjust the script file to reflect what you've mentioned, if that makes it easier

**Comment by nutterpc** [comment]
Although, having said that, I'm currently working on the wireless situation, and have managed to get it functioning (reported in the WP thread)

So as soon as i get another router (This ones hard bricked), I'll be able to continue

And as for the WAN connection, that's given me a a new direction & thing to try, so will form the basis of Release 2
