### ISSUE TITLE
tg800vac support?

### ISSUE THREAD

**Issue by nerfherder** [nutterpc/tg-luci#20]
Is there support planned for tg800vac?

**Comment by FrancYescO** [comment]
not needed, is already provided as an extension of https://github.com/Ansuel/tch-nginx-gui

**Comment by nerfherder** [comment]
It doesn't seem to be available as an extension for my install on tg800vac?  ![Screenshot_20200811-225156_Chrome (1).jpg](https://user-images.githubusercontent.com/2674434/89899246-51a6ad80-dc25-11ea-9d6e-855f3f97e583.jpg)

**Comment by FrancYescO** [comment]
Probably because no one tested it, you should try to manually issue the install commands.. open an enhancement issue on the tch-nginx-gui repo if you manage to test it
________________________________

**Comment by nerfherder** [comment]
Have tried to get it working, the install script failed with
'/lib/libuci.so' is not an ELF executable for ARM
I replaced libuci.so with the original file after the install but it doesn't load on at port 9080.

I'll keep playing around and see if I can get it to work.

**Comment by FrancYescO** [comment]
What commands have you used? The install script of tch-nginx GUI should already manage these things about libuci, you should not take anything from this repo that is for MIPS

**Comment by FrancYescO** [comment]
Test if with tch-nginx-gui 9.5.98 version you are able to install luci, move this conversation to https://github.com/Ansuel/tch-nginx-gui/issues otherwise.

**Comment by nerfherder** [comment]
The option is now there but the install fails. I think there is an error with opkg feeds. i'll update those manually and test.

Closing this thread to move to https://github.com/Ansuel/tch-nginx-gui/issues
